name: IPTV Playlist Generator

on:
  schedule:
    - cron: '15 */3 * * *'  # Every 3 hours at :15
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Environment
      run: |
        sudo apt-get update
        sudo apt-get install -y ffmpeg chromium-browser
        pip install yt-dlp browser-cookie3 --upgrade

    - name: Generate Playlist
      id: generator
      run: |
        chmod +x youtube_to_iptv.sh
        Xvfb :99 & DISPLAY=:99 ./youtube_to_iptv.sh
        echo "success=$(grep -c 'SUCCESS:' generator.log)" >> $GITHUB_OUTPUT

    - name: Upload Results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: results-${{ github.run_id }}
        path: |
          youtube_iptv.m3u
          generator.log

    - name: Commit Changes
      if: steps.generator.outputs.success > 0
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add youtube_iptv.m3u generator.log
        git commit -m "Update: ${{ steps.generator.outputs.success }} channels"
        git push
