name: Update IPTV Playlist

on:
  schedule:
    # Runs every 6 hours
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install yt-dlp
      run: pip install yt-dlp
      
    - name: Run update script
      run: |
        chmod +x update_playlist.sh
        ./update_playlist.sh
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
