name: Update IPTV Playlist

on:
  schedule:
    - cron: '0 */6 * * *'  # Every 6 hours
  workflow_dispatch:

permissions:
  contents: write  # This is crucial

jobs:
  update:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Important for git history
        
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install yt-dlp
      run: pip install yt-dlp
      
    - name: Run update script
      run: |
        chmod +x youtube_to_iptv.sh
        ./youtube_to_iptv.sh
      env:
        # No need for GITHUB_TOKEN here as actions/checkout handles it
