name: Update IPTV Playlist with Logos

on:
  schedule:
    - cron: '0 */6 * * *'  # Every 6 hours
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Get complete history

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y ffmpeg chromium-browser
        pip install yt-dlp browser-cookie3 --upgrade

    - name: Generate Playlist
      id: generator
      run: |
        mkdir -p ~/.config/youtube-dl
        chmod +x youtube_to_iptv.sh
        ./youtube_to_iptv.sh
        echo "success=$(grep -c 'SUCCESS:' generator.log)" >> $GITHUB_OUTPUT
        echo "playlist_lines=$(wc -l < youtube_iptv.m3u)" >> $GITHUB_OUTPUT

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playlist-artifacts
        path: |
          youtube_iptv.m3u
          generator.log

    - name: Commit and Push Changes
      if: steps.generator.outputs.success > 0
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git pull --rebase
        git add youtube_iptv.m3u generator.log
        git commit -m "Auto-update playlist with logos $(date +'%Y-%m-%d %H:%M')"
        git push
