name: Update IPTV Playlist

on:
  schedule:
    - cron: '0 */6 * * *'  # Runs every 6 hours
  workflow_dispatch:       # Allows manual triggering
  push:
    paths:
      - 'youtube_to_iptv.sh'  # Trigger when script changes

permissions:
  contents: write  # Required to push changes

jobs:
  update:
    runs-on: ubuntu-latest
    timeout-minutes: 15  # Prevent hanging
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Get complete git history

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y ffmpeg
        pip install --upgrade pip yt-dlp

    - name: Run Playlist Generator
      id: generator
      run: |
        chmod +x youtube_to_iptv.sh
        ./youtube_to_iptv.sh
        echo "success_count=$(grep -oP 'Successfully Added: \K\d+' generator.log)" >> $GITHUB_OUTPUT
        echo "playlist_lines=$(wc -l < youtube_iptv.m3u)" >> $GITHUB_OUTPUT

    - name: Show Results
      run: |
        echo "=== Generation Summary ==="
        cat generator.log | grep -A 10 "Generation Summary"
        echo ""
        echo "=== Last 10 Errors ==="
        grep -i error generator.log | tail -n 10 || echo "No errors found"

    - name: Commit and Push Changes
      if: steps.generator.outputs.success_count > 0
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add youtube_iptv.m3u generator.log
        git diff --cached --quiet || git commit -m "Auto-update playlist [$(date +'%Y-%m-%d %H:%M')]"
        git push
