name: Update IPTV Playlist

on:
  schedule:
    - cron: '0 */6 * * *'  # Every 6 hours
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y ffmpeg chromium-browser
        pip install yt-dlp browser-cookie3 --upgrade

    - name: Generate Playlist
      id: generate
      run: |
        mkdir -p ~/.config/youtube-dl
        chmod +x youtube_to_iptv.sh
        ./youtube_to_iptv.sh
        echo "success=$(grep -c 'SUCCESS:' generator.log)" >> $GITHUB_OUTPUT

    - name: Upload Debug Files
      uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: debug-files
        path: |
          youtube_iptv.m3u
          generator.log

    - name: Commit Changes
      if: steps.generate.outputs.success > 0
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add youtube_iptv.m3u generator.log
        git commit -m "Auto-update: $(date +'%Y-%m-%d %H:%M')"
        git push
