name: Update IPTV Playlist

on:
  schedule:
    - cron: '0 */6 * * *'  # Runs every 6 hours
  workflow_dispatch:       # Allows manual triggering

permissions:
  contents: write         # Required to push changes

jobs:
  update:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0    # Gets complete git history
        
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install yt-dlp
      run: pip install yt-dlp
      
    - name: Run update script
      run: |
        chmod +x youtube_to_iptv.sh
        ./youtube_to_iptv.sh
        
    - name: Push changes
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add youtube_iptv.m3u
        git commit -m "Auto-update playlist $(date +'%Y-%m-%d %H:%M:%S')"
        git push
